<a href="https://colab.research.google.com/github/Amrita-GitHub/somya-28-02-2025/blob/main/numpy_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def square(x):
  return x*x
print(square(5))


25


In [ ]:
result = lambda x: x*x
print(result(5))

25


In [ ]:
sq = np.vectorize(lambda x: x*x)
num = np.array([1,2,3,4,5])
print(sq(num))

[ 1  4  9 16 25]


In [ ]:
# filtering
# Sample array of sales figures
sales = np.array([100, 150, 200, 250, 300, 350, 400])

print(sales[sales>200])
print(sales[(sales >= 150) & (sales <= 350)])

# use the built in vectorized operations

print(sales[np.logical_and(sales >= 150,sales <= 350)])
print(sales[np.logical_or(sales < 150,sales > 350)])

# if then else
print(np.where(sales > 250, "Good", "Bad"))
# returns index when condition is met
print(np.where(sales>250))
# return the value when the condition is met
print(np.extract(sales>250,sales))

# normal looping
# for i in sales:
#   print(i)

for n in  np.nditer(sales):
  print(n)






[250 300 350 400]
[150 200 250 300 350]
[150 200 250 300 350]
[100 400]
['Bad' 'Bad' 'Bad' 'Bad' 'Good' 'Good' 'Good']
(array([4, 5, 6]),)
[300 350 400]
100
150
200
250
300
350
400


In [ ]:
num = np.array([1,2,3,4,5])
print(np.where(num>3,num*num,num))

[ 1  2  3 16 25]


In [ ]:
nnarray = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(np.apply_along_axis(np.sum,1,arr=nnarray))
print(np.apply_over_axes(np.sum, nnarray,axes=(0,1)))

[ 6 15 24]
[[45]]


In [ ]:
regional_sales = np.array([
    [100, 200, 150],
    [250, 300, 350],
    [400, 450, 500]
])
# sum of sales per region over days
print(np.apply_along_axis(np.sum,1,arr=regional_sales))


# acrross row
print(np.apply_along_axis(lambda r: np.max(r) - np.min(r),1,arr=regional_sales))
# across column
print(np.apply_along_axis(lambda r: np.max(r) - np.min(r),0,arr=regional_sales))
# sum of row and column
print(np.apply_over_axes(np.sum, regional_sales,axes=(0,1)))


[ 450  900 1350]
[100 100 100]
[300 250 350]
[[2700]]
