<a href="https://colab.research.google.com/github/Amrita-GitHub/somya-28-02-2025/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
num = [1,4,8,21,45]
type(num)

# num *= 2
# print(num)

# num += 2
# print(num)

for i in num:
    print(i *2)


2
8
16
42
90


In [16]:
# vectorized operations

import numpy as np
num = [1,4,8,21,45]

numarray = np.array(num)
type(numarray)

numarray *= 2
print(numarray)

numarray1 =  numarray > 40
numarray1

[ 2  8 16 42 90]


array([False, False, False,  True,  True])

In [14]:
# vectorized operations
sales = np.array([100, 150, 200, 250, 300])
discount_sales =  sales *.1
print(discount_sales)
final_sale  = sales - discount_sales
final_sale

[10. 15. 20. 25. 30.]


array([ 90., 135., 180., 225., 270.])

In [37]:
# use loops intsed of vectorization
sales1 = np.array([10, 20, 30, 40, 50])
discounted_sales = np.empty_like(sales1)
for i in  range(len(sales1)):
  discounted_sales = sales1[i] * .1
  print(discounted_sales)

1.0
2.0
3.0
4.0
5.0
